apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-jmx-config
data:
  prometheus.yaml: |2
    lowercaseOutputName: true
    attrNameSnakeCase: true
    rules:
      # Debugging rule
      # - pattern: ".*"
      #   name: jmx_debug_all
      #   type: GAUGE
      # Rules for sparkMeasure
      - pattern: sparkmeasure\.metrics<name=(\S+)\.(\S+)\.(\S+),\s*type=(\S+)><>Value
        name: sparkmeasure_$3_$4
        type: GAUGE
        labels:
          app_namespace: "$1"
          app_id: "$2"
      - pattern: sparkmeasure\.metrics<name=(\S+)\.(\S+)\.(\S+),\s*type=(\S+)><>Count
        name: sparkmeasure_$3_$4
        type: COUNTER
        labels:
          app_namespace: "$1"
          app_id: "$2"
      # Rules from https://github.com/prometheus/jmx_exporter/blob/main/examples/spark.yml
      - pattern: metrics<name=(\S+)\.(\S+)\.driver\.(BlockManager|DAGScheduler|jvm)\.(\S+)><>Value
        name: spark_driver_$3_$4
        type: GAUGE
        labels:
          app_namespace: "$1"
          app_id: "$2"
      - pattern: metrics<name=(\S+)\.(\S+)\.driver\.(\S+)\.StreamingMetrics\.streaming\.(\S+)><>Value
        name: spark_streaming_driver_$4
        type: GAUGE
        labels:
          app_namespace: "$1"
          app_id: "$2"
      - pattern: metrics<name=(\S+)\.(\S+)\.driver\.spark\.streaming\.(\S+)\.(\S+)><>Value
        name: spark_structured_streaming_driver_$4
        type: GAUGE
        labels:
          app_namespace: "$1"
          app_id: "$2"
          query_name: "$3"
      - pattern: metrics<name=(\S+)\.(\S+)\.(\S+)\.executor\.(\S+)><>Value
        name: spark_executor_$4
        type: GAUGE
        labels:
          app_namespace: "$1"
          app_id: "$2"
          executor_id: "$3"
      - pattern: metrics<name=(\S+)\.(\S+)\.driver\.DAGScheduler\.(.*)><>Count
        name: spark_driver_DAGScheduler_$3_count
        type: COUNTER
        labels:
          app_namespace: "$1"
          app_id: "$2"
      - pattern: metrics<name=(\S+)\.(\S+)\.driver\.HiveExternalCatalog\.(.*)><>Count
        name: spark_driver_HiveExternalCatalog_$3_count
        type: COUNTER
        labels:
          app_namespace: "$1"
          app_id: "$2"
      - pattern: metrics<name=(\S+)\.(\S+)\.driver\.CodeGenerator\.(.*)><>Count
        name: spark_driver_CodeGenerator_$3_count
        type: COUNTER
        labels:
          app_namespace: "$1"
          app_id: "$2"
      - pattern: metrics<name=(\S+)\.(\S+)\.driver\.LiveListenerBus\.(.*)><>Count
        name: spark_driver_LiveListenerBus_$3_count
        type: COUNTER
        labels:
          app_namespace: "$1"
          app_id: "$2"
      - pattern: metrics<name=(\S+)\.(\S+)\.driver\.LiveListenerBus\.(.*)><>Value
        name: spark_driver_LiveListenerBus_$3
        type: GAUGE
        labels:
          app_namespace: "$1"
          app_id: "$2"
      - pattern: metrics<name=(\S+)\.(\S+)\.(.*)\.executor\.(.*)><>Count
        name: spark_executor_$4_count
        type: COUNTER
        labels:
          app_namespace: "$1"
          app_id: "$2"
          executor_id: "$3"
      - pattern: metrics<name=(\S+)\.(\S+)\.([0-9]+)\.(jvm|NettyBlockTransfer)\.(.*)><>Value
        name: spark_executor_$4_$5
        type: GAUGE
        labels:
          app_namespace: "$1"
          app_id: "$2"
          executor_id: "$3"
      - pattern: metrics<name=(\S+)\.(\S+)\.([0-9]+)\.HiveExternalCatalog\.(.*)><>Count
        name: spark_executor_HiveExternalCatalog_$4_count
        type: COUNTER
        labels:
          app_namespace: "$1"
          app_id: "$2"
          executor_id: "$3"
      - pattern: metrics<name=(\S+)\.(\S+)\.([0-9]+)\.CodeGenerator\.(.*)><>Count
        name: spark_executor_CodeGenerator_$4_count
        type: COUNTER
        labels:
          app_namespace: "$1"
          app_id: "$2"
          executor_id: "$3"
