apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: argocd
  labels:
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/part-of: sparkmeasure
    app.kubernetes.io/component: operator
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: spark-operator
    repoURL: https://kubeflow.github.io/spark-operator
    targetRevision: 2.1.0
    helm:
      releaseName: spark-operator
      valuesObject:
        webhook:
          enable: true
        spark:
          # required by sparkJobNamespaces, to allow to create pods in spark application namespaces
          jobNamespaces: ["{{.Values.spec.sparkAppName}}"]
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: spark-operator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      # See https://github.com/argoproj/argo-cd/issues/820 and https://github.com/argoproj/argo-cd/issues/13100
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
